Added ARC I2C interfae library
01org/tinyTILE-Extended-Support-Library pull request #4
Opened 2016-09-12 08:43 UTC by xieqi

Support I2C controller ACI_I2C0 and ARC_I2C1 of the ARC Core.
@SidLeung

2016-09-12 17:16 UTC, eriknyquist commented on ARC_I2C/library.properties
> +sentence=This is a I2C libraries from the Arc core that are specific to the Randon+ hardware platform.
TinyTile, not Radon+

2016-09-12 17:17 UTC, eriknyquist commented
Are these all new files? or are they ported from somewhere?

2016-09-12 17:20 UTC, eriknyquist commented on ARC_I2C/library.properties
> +email=dave@emutex.com
Is this "author" accurate?

2016-09-12 17:30 UTC, eriknyquist commented
The file ARC_I2C.cpp is almost an exact duplicate of the existing file libraries/Wire/src/Wire.cpp; Besides the name change from "Wire" to "ARC_I2C", I can see perhaps 4-5 lines that are different.

Maybe the right approach here is to modify the existing driver so that a controller can be selected?

2016-09-12 17:40 UTC, eriknyquist commented
The two example sketches, also, are slightly modified versions of two existing Wire library examples.
Can we re-think this? this looks like about 95% duplication to me. Let's see if we can re-use the existing Wire API.

-1

2016-09-12 22:16 UTC, calvinatintel commented on ARC_I2C/library.properties
> +sentence=This is a I2C libraries from the Arc core that are specific to the Randon+ hardware platform.
tinyTILE

2016-10-31 18:41 UTC, eriknyquist requested changes
@xieqi any updates on this?

2016-10-31 21:36 UTC, closed without merging

2016-10-31 21:37 UTC, SidLeung commented
This PR is replaced by,

https://github.com/01org/tinyTILE-Extended-Support-Library/pull/5